Ercess/urls.py
from django.contrib import admin
from django.conf.urls import  url
from Ercesscorp import  views
from django.urls import  path ,re_path ,include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Ercesscorp.apiviews import *

# app_name = 'Ercess'


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home , name='home'),

    url(r'^accounts/login/$',views.loginview ,name='login'),

    url(r'^live/dashboard/', include('dashboard.urls')),
   # url(r'^live/dashboard/organizer_dashboard',views.manageevents),
    

    url(r'^home/$', views.home, name='home'),
    url(r'^live/$',views.home , name='home'),
    url(r'^live/verify_email/(?P<slug>[\w-]+)/$', views.verify_mail),
#    url(r'^live/verify_email/$', views.verify_mail, name='verify-email'),
    url(r'^live/forgot_password/$', views.forgotPassword, name='forgot-password'),
    url(r'^live/reset_password/(?P<slug>[\w-]+)/$', views.resetPassword),
    url(r'^live/set_new_password/$', views.setNewPassword),
#    url(r'^live/reset_password/$', views.resetPassword,name='reset-password'),
    url(r'^live/login/$', views.loginview, name='login'),
    url(r'^live/logout/$', views.logoutview, name='logout'),
    url(r'^live/signup/$', views.registration,name='signup'),
    url(r'^live/multichannel/$',views.multichannelpromotion,name='multichannel-promotion'),
    url(r'^live/sell_event_stalls/$',views.sellstallspaces, name='sell-event-stalls'),
    url(r'^live/paid_advertisement/$', views.advertisement,name='advertisement'),
    url(r'^live/how_it_works/$',views.howitworks, name='how-it-works'),
    url(r'^live/about/$',views.aboutus,name='about-us'),
    url(r'^live/contact/$',views.contactus,name='contact-us'),
    url(r'^live/blogs/$', views.blog, name='blog'),
    url(r'^live/blog-post/(?P<pk>[0-9]+)$', views.blogpost,name='blog-post'),
    url(r'^live/careers/$', views.career, name='careers'),
    url(r'^live/pricing/$', views.pricing, name='pricing'),
    url(r'^live/partners/$', views.partners, name='partners'),
    url(r'^live/privacy_policy/$', views.privacypolicy , name='privacy-policy'),
    url(r'^live/api/blogs/$' , BlogDetails.as_view(),name='blog-details'),
    url(r'^live/api/blogs/(?P<pk>[0-9]+)$', BlogSpecific.as_view(),name='blogspecific'),
    url(r'^live/api/users/$', Reg.as_view(),name='reg'),
    url(r'^live/api/login/$', LoginView.as_view(),'loginview'),
]



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)







Ercesscorp/models.py
from django.db import models
from django.contrib.auth.models import  User
# from datetime import  datetime


class RegistrationData(models.Model):
    user = models.OneToOneField(User, related_name='reg' , on_delete=models.DO_NOTHING)
    # mobile = models.BigIntegerField()
    gender = models.CharField(max_length=10 , default='blank' )
    location = models.CharField(max_length=30 , default='blank')
    submitted = models.IntegerField(default=0)
    how_u_know = models.CharField(max_length=100 , default='other')
    verify = models.IntegerField(default=0)





class BlogData(models.Model):
    blog_id = models.AutoField(primary_key=True)
    author = models.CharField(max_length=50 )
    title  = models.CharField(max_length=100)
    description = models.TextField()
    image = models.FileField(upload_to='images',default='images/business-events-cover-1.jpg' )
    date = models.DateTimeField()
    def __str__(self):
        return  self.title


class ContactData(models.Model):
    username = models.CharField(max_length=100 , null=False)
    email  = models.EmailField(max_length=70 , null=False)
    mobile = models.BigIntegerField(null=False)
    purpose = models.CharField(max_length=20, null=False)
    comment = models.CharField(max_length=1000 , null=False)
    def __str__(self):
        return  self.username

class Users(models.Model):
    social_userid = models.TextField(blank=True, null=True)
    md5 = models.CharField(max_length=300)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    user = models.CharField(max_length=40)
    profile_pic = models.TextField()
    gender = models.CharField(max_length=8)
    location = models.CharField(max_length=25)
    mobile = models.CharField(max_length=11)
    password = models.CharField(max_length=300, blank=True, null=True)
    mobile_verified = models.IntegerField(default=0)
    status = models.CharField(max_length=8, default='pending')
    first_time = models.CharField(max_length=10)
    organization_name = models.CharField(max_length=200)
    organization_location = models.TextField()

    class Meta:
        managed = False
        db_table = 'users'

class UserRegistrationToken(models.Model):
    user_email_token = models.CharField(max_length=250, default='')
    user_email_token_created_on = models.DateTimeField(null=True,blank=True)
    user_password_token = models.CharField(max_length=250, default='')
    user_email = models.CharField(max_length=250, default='')
    user_password_token_created_on = models.DateTimeField(null=True,blank=True)


Ercesscorp/forms.py
from django import  forms
import re
from multiselectfield import  MultiSelectFormField
from .porter import PURPOSE__CHOICES ,GENDER__CHOICES ,LOCATION__CHOICES



class UserForm(forms.Form):

    firstname = forms.CharField(
        # label='username',
        widget=forms.TextInput(

            attrs={
                # 'class': 'form-control',
                'placeholder': 'Firstname *'

            }
        )
    )
    lastname = forms.CharField(
        # label='username',
        widget=forms.TextInput(

            attrs={
                # 'class': 'form-control',
                'placeholder': 'Lastname *'

            }
        )
    )
    email = forms.EmailField(

        # label='email',
        widget=forms.EmailInput(

            attrs={
                # 'class': 'form-control',
                'placeholder': 'Email *'

            }

        )
    )

    # @author Shubham
    # Date: April 20 2019

    # confirmmail = forms.EmailField(

    #     # label='email',
    #     widget=forms.EmailInput(

    #         attrs={
    #             # 'class': 'form-control',
    #             'placeholder': 'Confirm Email *'
    #         }

    #     )
    # )
    # ends here ~ @author Shubham

    password = forms.CharField(

        # label='Password',
        widget=forms.PasswordInput(

            attrs={
                # 'class': 'form-control',
                'placeholder': 'Password *'

            }
        )
    )
    reenter_password = forms.CharField(

        # label='Re-enter password',
        widget=forms.PasswordInput(

            attrs={
                # 'class': 'form-control',
                'placeholder': 'Re-enter password *'

            }
        )
    )
    def clean_username(self):
        un  = self.cleaned_data['username']
        if len(un) <= 0 :
            raise forms.ValidationError('enter a valid username')
        return un
    def clean_email(self):
        el = self.cleaned_data['email']
        if  not re.match(r'\S+@\S+', el):
            raise forms.ValidationError('enter a valid email')
        return el
    # def clean(self):
    #     p1 = self.cleaned_data['password']
    #     p2 = self.cleaned_data['reenter_password']
    #     if  not (p1 == p2) :
    #         raise  forms.ValidationError('passwords are not matching')
    #     return p1 and p2


class RegistrationForm(forms.Form):
    # mobile = forms.IntegerField(
    #     widget= forms.NumberInput(
    #         attrs={
    #             'class':'form-control',
    #             'placeholder':'Mobile number *'
    #         }
    #
    #     )
    # )
    # location = forms.ChoiceField(choices=LOCATION__CHOICES)
    
    # @author Shubham
    # Date: April 20 2019

    location = forms.ChoiceField(choices=LOCATION__CHOICES)
    

    # location = forms.CharField(

    #     # label='Re-enter password',
    #     widget=forms.TextInput(

    #         attrs={
    #             # 'class': 'form-control',
    #             'placeholder': 'Location *'

    #         }
    #     )
    # )

    
    # gender = forms.ChoiceField(choices=GENDER__CHOICES)
    # ends here ~ @author Shubham


'''
class UserForm(forms.Form):

    firstname = forms.CharField(
        # label='username',
        widget=forms.TextInput(

            attrs={
                # 'class': 'form-control',
                'placeholder': 'Firstname *'

            }
        )
    )
    lastname = forms.CharField(
        # label='username',
        widget=forms.TextInput(

            attrs={
                # 'class': 'form-control',
                'placeholder': 'Lastname *'

            }
        )
    )
    email = forms.EmailField(

        # label='email',
        widget=forms.EmailInput(

            attrs={
                # 'class': 'form-control',
                'placeholder': 'Email *'

            }

        )
    )
    confirmmail = forms.EmailField(

        # label='email',
        widget=forms.EmailInput(

            attrs={
                # 'class': 'form-control',
                'placeholder': 'Confirm Email *'
            }

        )
    )
    password = forms.CharField(

        # label='Password',
        widget=forms.PasswordInput(

            attrs={
                # 'class': 'form-control',
                'placeholder': 'Password *'

            }
        )
    )
    reenter_password = forms.CharField(

        # label='Re-enter password',
        widget=forms.PasswordInput(

            attrs={
                # 'class': 'form-control',
                'placeholder': 'Re-enter password *'

            }
        )
    )
    def clean_username(self):
        un  = self.cleaned_data['username']
        if len(un) <= 0 :
            raise forms.ValidationError('enter a valid username')
        return un
    def clean_email(self):
        el = self.cleaned_data['email']
        if  not re.match(r'\S+@\S+', el):
            raise forms.ValidationError('enter a valid email')
        return el
    # def clean(self):
    #     p1 = self.cleaned_data['password']
    #     p2 = self.cleaned_data['reenter_password']
    #     if  not (p1 == p2) :
    #         raise  forms.ValidationError('passwords are not matching')
    #     return p1 and p2


class RegistrationForm(forms.Form):
    # mobile = forms.IntegerField(
    #     widget= forms.NumberInput(
    #         attrs={
    #             'class':'form-control',
    #             'placeholder':'Mobile number *'
    #         }
    #
    #     )
    # )
    # location = forms.ChoiceField(choices=LOCATION__CHOICES)
    location = forms.CharField(

        # label='Re-enter password',
        widget=forms.TextInput(

            attrs={
                # 'class': 'form-control',
                'placeholder': 'Location *'

            }
        )
    )
    gender = forms.ChoiceField(choices=GENDER__CHOICES)

'''

class LoginForm(forms.Form):
    email = forms.EmailField(
        # label='email',
        widget=forms.EmailInput(
            attrs={
                # 'class': 'form-control',
                'placeholder': 'Email *'
            }
        )
    )
    password = forms.CharField(

        # label='password',
        widget=forms.PasswordInput(

            attrs={
                # 'class': 'form-control',
                'placeholder': 'Password *'

            }
        ),
    )
    def clean_username(self):
        un = self.cleaned_data['username']
        if len(un) <= 0:
            raise forms.ValidationError('enter a valid username')
        return un

    def clean_password(self):
        ps = self.cleaned_data['password']
        if len(ps)<=0:
            raise forms.ValidationError('enter password')
        return ps



class ForgotPasswordForm(forms.Form):
    email = forms.EmailField(
        # label='email',
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Email *'

            }
        )
    )

    def clean_email(self):
        el = self.cleaned_data['email']
        if not re.match(r'\S+@\S+', el):
            raise forms.ValidationError('enter a valid email')
        return el


class ResetPassword(forms.Form):
    email = forms.EmailField(
        # label='email',
        widget=forms.EmailInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Email *'

            }
        )
    )
    password = forms.CharField(
        # label='username',
        widget=forms.PasswordInput(

            attrs={
                'class': 'form-control',
                'placeholder': 'Password *'

            }
        )
    )
    rpassword = forms.CharField(

        # label='password',
        widget=forms.PasswordInput(

            attrs={
                'class': 'form-control',
                'placeholder': 'Re enter password *'

            }
        ),
    )
    def clean_email(self):
        el = self.cleaned_data['email']
        if not re.match(r'\S+@\S+', el):
            raise forms.ValidationError('enter a valid email')
        return el
    def clean(self):
        ps = self.cleaned_data['password']
        rps = self.cleaned_data['rpassword']
        if len(ps)<=0:
            raise forms.ValidationError('enter password !')
        elif ps != rps:
            raise forms.ValidationError('passwords not matching !')
        return ps


class ContactForm(forms.Form):
    name = forms.CharField(
        # label='username',
        widget=forms.TextInput(

            attrs={
                'class': 'form-control',
                'placeholder': 'Name *'

            }
        )
    )
    email = forms.EmailField(

        # label='email',
        widget=forms.EmailInput(

            attrs={
                'class': 'form-control',
                'placeholder': 'Email *'

            }

        )
    )
    mobile = forms.IntegerField(
        widget=forms.NumberInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Mobile number *'
            }

        )
    )
    purpose =  forms.ChoiceField(choices=PURPOSE__CHOICES)
    comment = comment = forms.CharField(widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Your message *'
        }
    ))

class LegalForm(forms.Form):

    gstin = forms.CharField(max_length=15,label="GSTIN Number",
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder':'Enter your 15 digit GSTIN number'

            }

templates/Ercesscorp/fogotpassword.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">
    <head>
        <title>Enter your email to reset your password | Ercess Live</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1" />
        <meta name="description" content="Login to Ercess Live account to manage your events, promote, sell tickets, and sell stall spaces." />
        <link rel="shortcut icon" href="{% static 'images/fav.ico'%}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <meta name="google-site-verification" content="Hp-UR63f6b4b-tVU0rbbM4gE6AEHcRCbZ8vtbxRnpC4" />
        {% include 'static/common/css.html' %}
        <!--[if IE]>
            <script src="js/html5shiv.js"></script>
        <![endif]-->

        <style>
            body{
                background: #da2021;
            }
            label{
                visibility: hidden;
                display: none;
            }
            section{
                padding: 15px 0;
            }
            .box{
                width: 100%;
                padding: 30px;
                border-radius: 6px; 
                background: #ffffff;
            }
        </style>

        <script>
            $(window).on("load", function () {
                $("#id_email").addClass("big-input").removeClass('form-control');
            });

        </script>
    </head>
    <body>
        {% if usernotexist %}
            <div class="alert alert-danger" role="alert"><center>User does not exist !</center></div>
        {% elif errormail %}
            <div class="alert alert-danger" role="alert"><center>Unable to send mail ! Try after some time .</center></div>
        {% endif %}

        <section class="wow fadeIn" id="start-your-project">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-lg-4 visible-lg visible-md">
                        <img src="/static/images/signup-page.png" />
                    </div>
                    <div class = 'col-md-8 col-lg-8 text-center'>
                        <div class="box">
                            <a href="{% url 'home' %}" title="Ercess Live"><img src="/static/images/logo.png" /></a>
                            <p class="margin-40px-top">
                                Don't have an account? <b><u><a href="{% url 'signup' %}">Signup</a></u></b>
                            </p>
                            <div class="alert"></div>
                            <form method="post">
                                <label>Enter your email address</label>
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button type="button" class="btn btn-transparent-dark-gray btn-large margin-20px-top" onclick="forgetUserPassword()">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>
            {% include 'static/common/js.html' %}
    </body>

    <script type="text/javascript">

        toastr.options = {
            closeButton: true,
            newestOnTop: true,
            progressBar: true
        };
        function toastrErrorMsg(title, message) {
            toastr.error(message, title)
        }
        function toastrSuccessMsg(title, message) {
            toastr.success(message, title)
        }
        var emailRegex = /^[0-9a-zA-Z._-]{3,}@[a-zA-Z_]+?\.[a-zA-Z]{2,15}$/;

        function forgetUserPassword() {
            toastr.clear();
            let emalVal = $('#id_email')[0].value
            if(emalVal == '' || emalVal == undefined) {
                toastrErrorMsg("Error","Please enter your email address")
            } else if(emailRegex.test(emalVal) == false) {
                toastrErrorMsg("Error","Email address is invalid")
            } else {
                let userRegistrationPayload = {'emalVal':emalVal}
                $.ajax({
                    type: "POST",
                    dataType: "json",
                    url: "/live/forgot_password/",
                    data: JSON.stringify(userRegistrationPayload),
                    success: function(response) {
                        if(response.responseType == 'success') {
                            if(response.messageType == 'error') {
                                toastrErrorMsg("Error",response.message)
                            } else if(response.messageType == 'success') {
                                toastrSuccessMsg("Success",response.message)
                            }       
                        }
                    }
                });
            }
        }
    </script>
</html>

templates/Ercesscorp/registration.html
{% load static %}
<!doctype html>
<html class="no-js" lang="en">
    <head>
        <title>Create your new account on Ercess Live | Ercess Live</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1" />
        <meta name="description" content="Create your account on Ercess Live to manage and boost your events, promote, sell tickets, and stall spaces." />
        <link rel="shortcut icon" href="{% static 'images/fav.ico'%}">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <meta name="google-site-verification" content="Hp-UR63f6b4b-tVU0rbbM4gE6AEHcRCbZ8vtbxRnpC4" />
        {% include 'static/common/css.html' %}
        <!--[if IE]>
            <script src="js/html5shiv.js"></script>
        <![endif]-->

        <style>
            body{
                background: #da2021;
            }
            label{
                visibility: hidden;
                display: none;
            }
            section{
                padding: 15px 0;
            }
            .box{
                width: 100%;
                padding: 30px;
                border-radius: 6px; 
                background: #ffffff;
            }
        </style>

        <script>
            $(document).ready(function () {

                $("#id_username").addClass("big-input");
                $("#id_password").addClass("big-input");
                $("#id_email").addClass("big-input");
                $("#id_reenter_password").addClass("big-input");
                $("#id_mobile").addClass("big-input");
            });

        </script>
         <script>
            $(document).ready(function () {

                $("#id_firstname").addClass("bg-transparent border-color-medium-dark-gray big-input");
                $("#id_lastname").addClass("bg-transparent border-color-medium-dark-gray big-input");
                $("#id_password").addClass("bg-transparent border-color-medium-dark-gray big-input");
                $("#id_email").addClass("bg-transparent border-color-medium-dark-gray big-input");
                $("#id_confirmmail").addClass("bg-transparent border-color-medium-dark-gray big-input");
                $("#id_reenter_password").addClass("bg-transparent border-color-medium-dark-gray big-input");
                $("#id_gender").addClass("bg-transparent border-color-medium-dark-gray big-input");
                $("#id_location").addClass("bg-transparent border-color-medium-dark-gray big-input");

                $( "#fname" ).append( $( "#id_firstname" ) );
                $( "#lname" ).append( $( "#id_lastname" ) );
                $( "#emal" ).append( $( "#id_email" ) );
                $( "#cemal" ).append( $( "#id_confirmmail" ) );
                $( "#pass" ).append( $( "#id_password" ) );
                $( "#repass" ).append( $( "#id_reenter_password" ) );
                $( "#gen" ).append( $( "#id_gender" ) );
                $( "#loc" ).append( $( "#id_location" ) );

            });

        </script>
    </head>
    <body>
        {% if regerr %}
         <div class="alert alert-danger" role="alert"><center>This email address is already with us. Try to <a href="/live/login">Login</a> instead.</center></div>
        {% elif errormail %}
            <div class="alert alert-success" role="alert"><center>Registered sucessfully, but we failed to send email to you.</center></div>
        {% elif auth_email_failed %}
            <div class="alert alert-danger" role="alert"><center>Email verification failed.</center></div>
        {% elif submitted %}
          <div class="alert alert-success" role="alert"><center>Registered sucessfully, please check your mailbox to verify your email address.</center></div>
        {% elif pass_no_match %}
         <div class="alert alert-danger" role="alert"><center>Passwords are not matching.</center></div>
        {% endif %}

        <section class="wow fadeIn" id="start-your-project">
            <div class="container" id="completeFormDiv">
                <div class="row">
                    <div class="col-md-4 col-lg-4 visible-lg visible-md">
                        <img src="/static/images/signup-page.png" />
                    </div>
                    <div class = 'col-md-8 col-lg-8 text-center'>
                        <div class="box">

                            <a href="{% url 'home' %}" title="Ercess Live"><img src="/static/images/logo.png" /></a>
                            <p class="margin-40px-top">
                                Already have an account? <b><u><a href="/live/login">Login</a></u></b>
                            </p>
                            <form method="post">
                                {% csrf_token %}
                                    {{ form1.as_p }}
                                    {{ form2.as_p }}
                                        <br>
                                <div class="row">
                                    <div class="col-md-6 col-sm-12" id="fname"></div>
                                    <div class="col-md-6 col-sm-12" id="lname"></div>
                                    <div class="clearfix"></div>
                                    <div class="col-md-6 col-sm-12" id="loc"></div>
                                    <div class="col-md-6 col-sm-12" id="emal"></div>
                                    <div class="clearfix"></div>
                                    <div class="col-md-6 col-sm-12" id="pass"></div>
                                    <div class="col-md-6 col-sm-12" id="repass"></div >
                                    <div class="clearfix"></div>
                                    <div class="col-md-12">
                                        <button type="button" class="btn btn-transparent-dark-gray btn-large margin-20px-top" onclick="submitUserDetails()">CREATE ACCOUNT</button>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </section>

            {% include 'static/common/js.html' %}
    </body>

    <script type="text/javascript">
        toastr.options = {
            closeButton: true,
            newestOnTop: true,
            progressBar: true
        };
        function toastrErrorMsg(title, message) {
            toastr.error(message, title)
        }
        function toastrSuccessMsg(title, message) {
            toastr.success(message, title)
        }

        var emailRegex = /^[0-9a-zA-Z._-]{3,}@[a-zA-Z_]+?\.[a-zA-Z]{2,15}$/;
        var nameRegex = /^[a-zA-Z\s]*$/;

        function submitUserDetails() {

            toastr.clear();

            var fnameVal = $('#id_firstname')[0].value
            var lnameVal = $('#id_lastname')[0].value
            var locVal = $('#id_location')[0].value
            var emalVal = $('#id_email')[0].value
            var passVal = $('#id_password')[0].value
            var repassVal = $('#id_reenter_password')[0].value


            if(fnameVal == '' || fnameVal == undefined) {
                toastrErrorMsg("Error","Please enter your First Name")
            } else if(nameRegex.test(fnameVal) == false) {
                toastrErrorMsg("Error","First Name is invalid. Only alphabets are allowed.")
            } else if(lnameVal == '' || lnameVal == undefined) {
                toastrErrorMsg("Error","Please enter your Last Name")
            } else if(nameRegex.test(lnameVal) == false) {
                toastrErrorMsg("Error","Last Name is invalid. Only alphabets are allowed.")
            } else if(locVal == '' || locVal == undefined) {
                toastrErrorMsg("Error","Please select your Country.")
            } else if(emalVal == '' || emalVal == undefined) {
                toastrErrorMsg("Error","Please enter your Email.")
            } else if(emailRegex.test(emalVal) == false) {
                toastrErrorMsg("Error","Email address is Invalid.")
            } else if(passVal == '' || passVal == undefined || passVal.length < 8) {
                toastrErrorMsg("Error","Password length should be minimum 8 characters.")
            } else if(repassVal == '' || repassVal == undefined) {
                toastrErrorMsg("Error","Please enter in Confirm Password.")
            } else if(passVal != repassVal) {
                toastrErrorMsg("Error","Both passwords do not match.")
            } else {
                var userRegistrationPayload = {'fnameVal':fnameVal,'lnameVal':lnameVal,'locVal':locVal, 'emalVal':emalVal, 'passVal':passVal}

                $.ajax({
                    type: "POST",
                    dataType: "json",
                    url: "/live/signup/",
                    data: JSON.stringify(userRegistrationPayload),
                    success: function(response) {
                        if(response.responseType == 'success') {
                            if(response.messageType == 'success') {
                                let messageBoxData = '<div style="color: white;background: #555555;text-align: center;padding: 20px;border-radius: 8px;font-size: 18px;">'+ response.message+'</div>'
                                document.getElementById('completeFormDiv').innerHTML = messageBoxData
                            } else if(response.messageType == 'error') {
                                toastrErrorMsg("Error",response.message)
                            }
                        }
                    }
                });
                
            }
        }
    </script>

</html>