Ercess/urls.py
from django.contrib import admin
from django.conf.urls import  url
from Ercesscorp import  views
from django.urls import  path ,re_path ,include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Ercesscorp.apiviews import *

# app_name = 'Ercess'


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home , name='home'),

    url(r'^accounts/login/$',views.loginview ,name='login'),

    url(r'^live/dashboard/', include('dashboard.urls')),
   # url(r'^live/dashboard/organizer_dashboard',views.manageevents),
    

    url(r'^home/$', views.home, name='home'),
    url(r'^live/$',views.home , name='home'),
    url(r'^live/verify_email/(?P<slug>[\w-]+)/$', views.verify_mail),
#    url(r'^live/verify_email/$', views.verify_mail, name='verify-email'),
    url(r'^live/forgot_password/$', views.forgotPassword, name='forgot-password'),
    url(r'^live/reset_password/(?P<slug>[\w-]+)/$', views.resetPassword),
    url(r'^live/set_new_password/$', views.setNewPassword),
#    url(r'^live/reset_password/$', views.resetPassword,name='reset-password'),
    url(r'^live/login/$', views.loginview, name='login'),
    url(r'^live/logout/$', views.logoutview, name='logout'),
    url(r'^live/signup/$', views.registration,name='signup'),
    url(r'^live/multichannel/$',views.multichannelpromotion,name='multichannel-promotion'),
    url(r'^live/sell_event_stalls/$',views.sellstallspaces, name='sell-event-stalls'),
    url(r'^live/paid_advertisement/$', views.advertisement,name='advertisement'),
    url(r'^live/how_it_works/$',views.howitworks, name='how-it-works'),
    url(r'^live/about/$',views.aboutus,name='about-us'),
    url(r'^live/contact/$',views.contactus,name='contact-us'),
    url(r'^live/blogs/$', views.blog, name='blog'),
    url(r'^live/blog-post/(?P<pk>[0-9]+)$', views.blogpost,name='blog-post'),
    url(r'^live/careers/$', views.career, name='careers'),
    url(r'^live/pricing/$', views.pricing, name='pricing'),
    url(r'^live/partners/$', views.partners, name='partners'),
    url(r'^live/privacy_policy/$', views.privacypolicy , name='privacy-policy'),
    url(r'^live/api/blogs/$' , BlogDetails.as_view(),name='blog-details'),
    url(r'^live/api/blogs/(?P<pk>[0-9]+)$', BlogSpecific.as_view(),name='blogspecific'),
    url(r'^live/api/users/$', Reg.as_view(),name='reg'),
    url(r'^live/api/login/$', LoginView.as_view(),'loginview'),
]



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)







dashboard/urls.py
from django.urls import path, include
from django.conf.urls import  url
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import TemplateView

from Ercesscorp.third_party_security import smartlogin
from Ercesscorp import views
from Ercesscorp.views import edit_event,step_three,step_three_action,edit_action_one,edit_event_two,edit_event_four,edit_action_four,edit_action_four
from dashboard.views import  getHow, change_password #, third_step#,photo_list ,fourth_step
from .api.views import ( ArticlesCreateAPIView, CategoryCreateAPIView, 
                        TopicsListAPIView, DescriptionCreateAPIView,
                        ThirdStepTemp, QuestionCreateAPIView,
                        CreateTicketsView, BankDetailsView)

from .views import  EditDetailView


app_name = 'dashboard'

urlpatterns = [
    url(r'^$', getHow, name='how'),
    path('add-event', ArticlesCreateAPIView.as_view(), name="step_one"),
    path('add-event-types/<str:md5>/<int:event_id>', CategoryCreateAPIView.as_view(), name="step_two"),
    path('add-event-images/<str:md5>/<int:event_id>', views.step_three, name="step_three"),
    path('add-event-images-action/<str:md5>/<int:event_id>', views.step_three_action, name="step_three_action"),
    path('ajax/topics', TopicsListAPIView.as_view()),
    path('add-event-description/<str:md5>/<int:event_id>', DescriptionCreateAPIView.as_view(), name="step_four"),
    path('add-event-tickets/<str:md5>/<int:event_id>', CreateTicketsView.as_view(), name="step_five"),
    path('add-event-question/<str:md5>/<int:event_id>', QuestionCreateAPIView.as_view(), name="step_six"),
    path('event_added', TemplateView.as_view(template_name='dashboard/event_success.html'), name='event_added'),
    path('RSVP',views.RSVP,name='leads'),
    path('rsvp/<int:event_id>',views.rsvp_event,name='rsvp-event'),
    path('organizer_dashboard',views.manageevents, name='organizer-dashboard'),
    path('event-details/<int:event_id>',views.event_details, name='event-details'),
    path('sales', views.getSales, name='sales'),
    path('sales_details/<int:event_id>/',views.getSalesDetails, name ='sale_details'),
    path('inquiries', views.getInquiries, name='inquiries'),
    path('help',views.getHelp,name='help'),
    path('profile',views.profile,name='profile'),
    path('settings', change_password,name='settings'),
    path('legal',views.legal,name='legal'),
    path('bank-details',BankDetailsView.as_view(), name="bank_details"),
    path('create-stalls',views.create_stall, name="create_stall"),
    path('edit-event/<int:event_id>', EditDetailView.as_view(), name="detail"),
    path('edit-event/basic/<int:event_id>',views.edit_event, name='edit-event'),
    path('edit-event-two/<int:event_id>',views.edit_event_two, name='edit-event-two'),
    path('edit-event-four/<int:event_id>',views.edit_event_four, name='edit-event-four'),
    path('edit_action_one/<event_id>',views.edit_action_one, name='edit-action-one'),
    path('edit_action_two/<event_id>',views.edit_action_two, name='edit-action-two'),
    path('edit_action_four/<event_id>',views.edit_action_four, name='edit-action-four'),
    #path('legal',views.legal,name='legal'),
    #url(r'create-event/step-three/(?P<eventid>[0-9]+)$',login_required(third_step),name='third-step'),
    #url(r'test$',photo_list),
    #url(r'create-event/step-four/$',login_required(fourth_step),name='fourth-step')
    # url(r'^home',home,name='home'),

    # url(r'^live/dashboard/organizer_dashboard',views.manageevents),
    # url(r'^live/dashboard/sales',views.salesreport),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/edit_detail.html
{% extends "dashboard/create_event.html" %}
{% load static %}
{% block title %} Edit your event - Ercess Live {% endblock title %}

{% block og %}
<section class="content">
    <div class="container arrow-steps clearfix">
        <div class="row">
            <div class="col-md-12">
              <h1 class="text-dark mb-30">Edit {{ article.event_name}}</h1>
              <ul class="nav nav-tabs">
                  <li class="nav-item">
                      <a class="nav-link active" data-toggle="tab" href="#basic">Basic</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#targets">Targets</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#images">Images</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#description">Description</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#tickets">Tickets</a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link" data-toggle="tab" href="#custom-question">Custom Question</a>
                  </li>
              </ul>

              <div class="tab-content">

                <div id="basic" class="tab-pane active">
                  <div class="row">
                    <div class="col-md-8 mb-30">
                      <h3 class="dark-grey-text">Event Name:</h3>
                      <p>{{ article.event_name}}</p>
                    </div>
                    <div class="col-md-4 float-right">
                      <div class="float-right">
                        <a class="btn btn1 btn-danger mt-15" href="{% url 'dashboard:edit-event' article.id  %}"><i class="fa fa-pencil"></i> Edit</a>
                      </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-md-6 mb-30">
                      <h4 class="dark-grey-text">Start date:</h4>
                      <p >{{ article.sdate|date:'Y-m-d'}}</p>
                    </div>
                    <div class="col-md-6">
                      <h4 class="dark-grey-text">Start time:</h4>
                      <p class="text-uppercase">{{ article.start_time }}</p>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-md-6 mb-30">
                      <h4 class="dark-grey-text">End date:</h4>
                      <p>{{ article.edate |date:'Y-m-d'}}</p>
                    </div>
                    <div class="col-md-6">
                      <h4 class="dark-grey-text">End time:</h4>
                      <p class="text-uppercase">{{ article.end_time }}</p>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-md-6 mb-30">
                      <h4 class="dark-grey-text">Address line 1:</h4>
                      <p>{{ article.address_line1}}</p>
                    </div>
                    <div class="col-md-6">
                      <h4 class="dark-grey-text">Address line 2:</h4>
                      <p>{{ article.address_line2}}</p>
                    </div>
                    <div class="clearfix"></div>
                    <div class="col-md-3 mb-30">
                      <h4 class="dark-grey-text">Pincode:</h4>
                      <p>{{ article.pincode}}</p>
                    </div>
                    <div class="col-md-3">
                      <h4 class="dark-grey-text">City:</h4>
                      <p>{{ article.city}}</p>
                    </div>
                    <div class="col-md-3">
                      <h4 class="dark-grey-text">State:</h4>
                      <p>{{ article.state}}</p>
                    </div>
                    <div class="col-md-3">
                      <h4 class="dark-grey-text">Country:</h4>
                      <p>{{ article.country}}</p>
                    </div>
                  </div>
                </div>
                  <div id="targets" class="tab-pane ">
                      <a  href="{% url 'dashboard:edit-event-two' article.id  %}">Edit</a>
                  </div>
                  <div id="images" class="tab-pane ">
                      <h4 class="dark-grey-text">Profile Image</h4>
                      <p>{{ article.profile_image }}</p>
                      <img src="{{ article.profile_image.url }}" alt="">

                      <h4 class="dark-grey-text">Banner</h4>
                      <img src="{{ article.banner.url }}" alt="">
                  </div>
                  <div id="description" class="tab-pane ">
                      <div class="row">
                        <div class="col-md-9 mb-30">
                          <h3 class="dark-grey-text">Description:</h3>
                          {{ article.description | safe}}
                        </div>
                        <div class="col-md-3 float-right">
                          <div class="float-right">
                            <a class="btn btn1 btn-danger mt-15" href="{% url 'dashboard:edit-event' article.id  %}"><i class="fa fa-pencil"></i> Edit</a>
                          </div>
                        </div>
                      </div>
                  </div>
                  <div id="tickets" class="tab-pane ">
                      <h4>Ticket Details:</h4>
                      <div class="col-md-6  mb-30">
                        <h4>Ticket Name : </h4>
                      <p>{{ tickets.ticket_name }}</p>
                      </div>
                      <div class="col-md-6 mb-30">
                      <h4>Ticket Price:</h4>
                      <p>{{ tickets.ticket_price }}</p>
                      </div>
                      <div class="col-md-6 mb-30">
                      <h4>Quantity:</h4>
                      <p>{{ tickets.ticket_qty }}</p>
                      </div>
                      <div class="col-md-6 mb-30">
                      <h4>Other Charges:</h4>
                      <p>{{ tickets.other_charges }}</p>
                      </div>

                  </div>
                  <div id="custom-question" class="tab-pane ">
                  </div>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>
{% endblock og %}

templates/edit_list.html
<html>
  <body>
    <h1>Events</h1>
    <h3>Basic</h3>
    <ul>
      {% for article in Articles %}
      <li>{{ article.id }}</li>
      <li>{{ article.event_name }}</li>
      <li>{{ article.md5 }}</li>
      <li>{{ article.address_line1 }}</li>
      <li>{{ article.address_line2 }}</li>
      <li>{{ article.pincode }}</li>
      <li>{{ article.state }}</li>
      <li>{{ article.city }}</li>
      <h3>Images</h3>
      <li>{{ article.banner }}</li>
      <li>{{ article.editable_image }}</li>

      <h3>Target</h3>

      <li>{{ article.date_added }}</li>
      <li>{{ article.sdate }}</li>
      <li>{{ article.edate }}</li>
      <li>{{ article.start_time }}</li>
      <li>{{ article.end_time }}</li>

      <h3>Description</h3>

      <li>{{ article.description }}</li>

      <h3>Tickets</h3>
      <li>{{ article.ticket_url }}</li>
      {% endfor %}
    </ul>
  </body>
</html>