Ercess/urls.py
from django.contrib import admin
from django.conf.urls import  url
from Ercesscorp import  views
from django.urls import  path ,re_path ,include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Ercesscorp.apiviews import *

# app_name = 'Ercess'


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home , name='home'),

    url(r'^accounts/login/$',views.loginview ,name='login'),

    url(r'^live/dashboard/', include('dashboard.urls')),
   # url(r'^live/dashboard/organizer_dashboard',views.manageevents),
    

    url(r'^home/$', views.home, name='home'),
    url(r'^live/$',views.home , name='home'),
    url(r'^live/verify_email/(?P<slug>[\w-]+)/$', views.verify_mail),
#    url(r'^live/verify_email/$', views.verify_mail, name='verify-email'),
    url(r'^live/forgot_password/$', views.forgotPassword, name='forgot-password'),
    url(r'^live/reset_password/(?P<slug>[\w-]+)/$', views.resetPassword),
    url(r'^live/set_new_password/$', views.setNewPassword),
#    url(r'^live/reset_password/$', views.resetPassword,name='reset-password'),
    url(r'^live/login/$', views.loginview, name='login'),
    url(r'^live/logout/$', views.logoutview, name='logout'),
    url(r'^live/signup/$', views.registration,name='signup'),
    url(r'^live/multichannel/$',views.multichannelpromotion,name='multichannel-promotion'),
    url(r'^live/sell_event_stalls/$',views.sellstallspaces, name='sell-event-stalls'),
    url(r'^live/paid_advertisement/$', views.advertisement,name='advertisement'),
    url(r'^live/how_it_works/$',views.howitworks, name='how-it-works'),
    url(r'^live/about/$',views.aboutus,name='about-us'),
    url(r'^live/contact/$',views.contactus,name='contact-us'),
    url(r'^live/blogs/$', views.blog, name='blog'),
    url(r'^live/blog-post/(?P<pk>[0-9]+)$', views.blogpost,name='blog-post'),
    url(r'^live/careers/$', views.career, name='careers'),
    url(r'^live/pricing/$', views.pricing, name='pricing'),
    url(r'^live/partners/$', views.partners, name='partners'),
    url(r'^live/privacy_policy/$', views.privacypolicy , name='privacy-policy'),
    url(r'^live/api/blogs/$' , BlogDetails.as_view(),name='blog-details'),
    url(r'^live/api/blogs/(?P<pk>[0-9]+)$', BlogSpecific.as_view(),name='blogspecific'),
    url(r'^live/api/users/$', Reg.as_view(),name='reg'),
    url(r'^live/api/login/$', LoginView.as_view(),'loginview'),
]



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)







dashboard/urls.py
from django.urls import path, include
from django.conf.urls import  url
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import TemplateView

from Ercesscorp.third_party_security import smartlogin
from Ercesscorp import views
from Ercesscorp.views import edit_event,step_three,step_three_action,edit_action_one,edit_event_two,edit_event_four,edit_action_four,edit_action_four
from dashboard.views import  getHow, change_password #, third_step#,photo_list ,fourth_step
from .api.views import ( ArticlesCreateAPIView, CategoryCreateAPIView, 
                        TopicsListAPIView, DescriptionCreateAPIView,
                        ThirdStepTemp, QuestionCreateAPIView,
                        CreateTicketsView, BankDetailsView)

from .views import  EditDetailView


app_name = 'dashboard'

urlpatterns = [
    url(r'^$', getHow, name='how'),
    path('add-event', ArticlesCreateAPIView.as_view(), name="step_one"),
    path('add-event-types/<str:md5>/<int:event_id>', CategoryCreateAPIView.as_view(), name="step_two"),
    path('add-event-images/<str:md5>/<int:event_id>', views.step_three, name="step_three"),
    path('add-event-images-action/<str:md5>/<int:event_id>', views.step_three_action, name="step_three_action"),
    path('ajax/topics', TopicsListAPIView.as_view()),
    path('add-event-description/<str:md5>/<int:event_id>', DescriptionCreateAPIView.as_view(), name="step_four"),
    path('add-event-tickets/<str:md5>/<int:event_id>', CreateTicketsView.as_view(), name="step_five"),
    path('add-event-question/<str:md5>/<int:event_id>', QuestionCreateAPIView.as_view(), name="step_six"),
    path('event_added', TemplateView.as_view(template_name='dashboard/event_success.html'), name='event_added'),
    path('RSVP',views.RSVP,name='leads'),
    path('rsvp/<int:event_id>',views.rsvp_event,name='rsvp-event'),
    path('organizer_dashboard',views.manageevents, name='organizer-dashboard'),
    path('event-details/<int:event_id>',views.event_details, name='event-details'),
    path('sales', views.getSales, name='sales'),
    path('sales_details/<int:event_id>/',views.getSalesDetails, name ='sale_details'),
    path('inquiries', views.getInquiries, name='inquiries'),
    path('help',views.getHelp,name='help'),
    path('profile',views.profile,name='profile'),
    path('settings', change_password,name='settings'),
    path('legal',views.legal,name='legal'),
    path('bank-details',BankDetailsView.as_view(), name="bank_details"),
    path('create-stalls',views.create_stall, name="create_stall"),
    path('edit-event/<int:event_id>', EditDetailView.as_view(), name="detail"),
    path('edit-event/basic/<int:event_id>',views.edit_event, name='edit-event'),
    path('edit-event-two/<int:event_id>',views.edit_event_two, name='edit-event-two'),
    path('edit-event-four/<int:event_id>',views.edit_event_four, name='edit-event-four'),
    path('edit_action_one/<event_id>',views.edit_action_one, name='edit-action-one'),
    path('edit_action_two/<event_id>',views.edit_action_two, name='edit-action-two'),
    path('edit_action_four/<event_id>',views.edit_action_four, name='edit-action-four'),
    #path('legal',views.legal,name='legal'),
    #url(r'create-event/step-three/(?P<eventid>[0-9]+)$',login_required(third_step),name='third-step'),
    #url(r'test$',photo_list),
    #url(r'create-event/step-four/$',login_required(fourth_step),name='fourth-step')
    # url(r'^home',home,name='home'),

    # url(r'^live/dashboard/organizer_dashboard',views.manageevents),
    # url(r'^live/dashboard/sales',views.salesreport),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/dashboard/create-event/step_3/step_three_temp.html
{% extends "dashboard/create_event.html" %}
{% load rest_framework %}
{% load static %}
{% block title %}Upload Images - Ercess Live{% endblock title %}

{% block step_three %}



<section class="content">
    <div class="container arrow-steps clearfix">
        <div class="row">
            <div class="col-md-12">
                <h1 class="text-dark mb-30">Upload Images</h1>
                <div class="md-stepper-horizontal red">
                    <div class="md-step active done">
                      <div class="md-step-circle"><span>1</span></div>
                      <div class="md-step-title">Basic details</div>
                      <div class="md-step-bar-left"></div>
                      <div class="md-step-bar-right"></div>
                    </div>
                    <div class="md-step active done">
                      <div class="md-step-circle"><span>2</span></div>
                      <div class="md-step-title">Set targets</div>
                      <div class="md-step-bar-left"></div>
                      <div class="md-step-bar-right"></div>
                    </div>
                    <div class="md-step active">
                      <div class="md-step-circle"><span>3</span></div>
                      <div class="md-step-title">Upload images</div>
                      <div class="md-step-bar-left"></div>
                      <div class="md-step-bar-right"></div>
                    </div>
                    <div class="md-step">
                      <div class="md-step-circle"><span>4</span></div>
                      <div class="md-step-title">Description</div>
                      <div class="md-step-bar-left"></div>
                      <div class="md-step-bar-right"></div>
                    </div>
                    <div class="md-step">
                      <div class="md-step-circle"><span>5</span></div>
                      <div class="md-step-title">Add tickets</div>
                      <div class="md-step-bar-left"></div>
                      <div class="md-step-bar-right"></div>
                    </div>
                    <div class="md-step">
                      <div class="md-step-circle"><span>6</span></div>
                      <div class="md-step-title">Custom questions</div>
                      <div class="md-step-bar-left"></div>
                      <div class="md-step-bar-right"></div>
                    </div>
                </div>

            </div>
        </div>

    </div>


    <form action="{% url 'dashboard:step_three_action' md5 event_id %}" enctype="multipart/form-data" method="POST" id="msform1" class="col-md-12 mt-50 mb-50" autocomplete="off">    {% csrf_token %}
        <fieldset>
            <div class="row">
            <div class="form-group col-md-6" >
                <label>Thumbnail</label>
                
                  <input id="menu_images1" class="form-control" type="file"  name="myfile1" >
                  <p>Kindly Upload your company logo only</p>
                  <img id="menu_image1" class="preview_img1" />
                  <div id="e1" style="display: none;" class="alert alert-danger">
                      <strongn id="error1" style="color: white"></strong>
                   </div>
                  
                  
            </div>
            

            <div class="form-group col-md-6" >
            <label>Banner Image</label>
                
                  <input id="menu_images" class="form-control" type="file"  name="myfile" required>
                  <img id="menu_image" class="preview_img" />
                  <div id="e" class="alert alert-danger" style="display: none;">
                      <strongn id="error" style="color: white;"></strong>
                   </div>
                </div>
              

            <div class="form-group col-12" >
                <label>Editable Image</label>
                
                  <input id="menu_images2" class="form-control block" type="file"  name="myfile2">
                  <img id="menu_image2" class="preview_img2" />
                  <div id="e2" style="display: none;" class="alert alert-danger">
                      <strongn id="error2" class="align-middle" style="color: white"></strong>
                   </div>
            </div>
          
  
            <button type="submit" class="btn btn1 btn-danger btn-block mt-10">Upload</button>



        </fieldset>
    </form>
    <!-- <img src="{% static '/images/events/1.jpg' %}"> -->
    

  </section>


    
    <script>
document.getElementById("menu_images").onchange = function () {

     var reader = new FileReader();

                var _URL = window.URL || window.webkitURL;
                let file = this.files[0]
                let image = new Image()

                image.src = _URL.createObjectURL(file);


                image.onload = function () {
                  console.log(this.width)
                  console.log(this.height)
                  console.log(this.width<this.height)
                  if(this.width < 800){
                          document.getElementById('e').style.display = "block";
                          if(document.getElementById("error").innerText == 'Width should be more than 800 px'){
                            document.getElementById("error").innerHTML = '';
                          }
                          else{
                          document.getElementById("error").innerHTML = "Width should be more than 800 px" ;
                          }
                          $("#menu_image").attr("src","blank");
                          $("#menu_image").hide();  
                          $('#menu_images').wrap('<form>').closest('form').get(0).reset();
                          $('#menu_images').unwrap();     
                          return false;
                  }
                  if(this.width < this.height){
                    console.log('width is smaller')
                      document.getElementById('e').style.display = "block";
                      if(document.getElementById("error").innerText == 'Image should be horizontally longer'){
                          document.getElementById("error").innerHTML = '';
                        }
                        else{
                        document.getElementById("error").innerHTML = "Image should be horizontally longer" ;
                        }
                        $("#menu_image").attr("src","blank");
                      $("#menu_image").hide();  
                      $('#menu_images').wrap('<form>').closest('form').get(0).reset();
                      $('#menu_images').unwrap();     
                      return false;
                           
                  }
                }
   
    document.getElementById('e').style.display = "none";

    if(this.files[0].size>2097152){
        document.getElementById('e').style.display = "block";
        if(document.getElementById("error").innerText == 'Image Size should not be greater than 2 MB'){
              document.getElementById("error").innerHTML = '';
            }
            else{
            document.getElementById("error").innerHTML = "Image Size should not be greater than 2 MB" ;
            }




        $("#menu_image").attr("src","blank");
        $("#menu_image").hide();  
        $('#menu_images').wrap('<form>').closest('form').get(0).reset();
        $('#menu_images').unwrap();     
        return false;
    }

    if(this.files[0].type.indexOf("image")==-1){
        document.getElementById('e').style.display = "block";
        if(document.getElementById("error").innerText == 'Invalid Type'){
              document.getElementById("error").innerHTML = '';
            }
            else{
            document.getElementById("error").innerHTML = "Invalid Type" ;
            }
        
        $("#menu_image").attr("src","blank");
        $("#menu_image").hide();  
        $('#menu_images').wrap('<form>').closest('form').get(0).reset();
        $('#menu_images').unwrap();         
        return false;
    }   
    // if(this.files[0].type !== 'image/png'){
    //     document.getElementById('e').style.display = "block";
    //     if(document.getElementById("error").innerText == 'Only png format allowed.'){
    //           document.getElementById("error").innerHTML += '';
    //         }
    //         else{
    //         document.getElementById("error").innerHTML += 'Only png format allowed.' ;
    //         }
        
    //     $("#menu_image").attr("src","blank");
    //     $("#menu_image").hide();  
    //     $('#menu_images').wrap('<form>').closest('form').get(0).reset();
    //     $('#menu_images').unwrap();         
    //     return false;
    // }   
    reader.onload = function (e) {
        // get loaded data and render thumbnail.
        document.getElementById("menu_image").src = e.target.result;
        $("#menu_image").show(); 
    };

    // read the image file as a data URL.
    reader.readAsDataURL(this.files[0]);
};


document.getElementById("menu_images1").onchange = function () {

    var reader = new FileReader();
    document.getElementById('e1').style.display = "none";

      var _URL = window.URL || window.webkitURL;
                let file = this.files[0]
                let image = new Image()

                image.src = _URL.createObjectURL(file);


                image.onload = function () {
                  console.log(this.width)
                  console.log(this.height)
                  console.log(this.width<this.height)
                  if(this.width !== this.height){
                          document.getElementById('e1').style.display = "block";
                          if(document.getElementById("error1").innerText == 'Image should be squared'){
                            document.getElementById("error1").innerHTML = '';
                          }
                          else{
                          document.getElementById("error1").innerHTML = "Image should be squared" ;
                          }
                          $("#menu_image1").attr("src","blank");
                          $("#menu_image1").hide();  
                          $('#menu_images1').wrap('<form>').closest('form').get(0).reset();
                          $('#menu_images1').unwrap();     
                          return false;
                  }
  
                }

    if(this.files[0].size>2097152){
        document.getElementById('e1').style.display = "block";
        
        if(document.getElementById("error1").innerText == 'Image Size should not be greater than 2 MB'){
              document.getElementById("error1").innerHTML = '';
            }
            else{
            document.getElementById("error1").innerHTML = "Image Size should not be greater than 2 MB" ;
            }
        
        $("#menu_image1").attr("src","blank");
        $("#menu_image1").hide();  
        $('#menu_images1').wrap('<form>').closest('form').get(0).reset();
        $('#menu_images1').unwrap();     
        return false;
    }

    if(this.files[0].type.indexOf("image")==-1){
        document.getElementById('e1').style.display = "block";
        if(document.getElementById("error1").innerText == 'Invalid Type'){
              document.getElementById("error1").innerHTML = '';
            }
            else{
            document.getElementById("error1").innerHTML = "Invalid Type" ;
            }
        
        $("#menu_image1").attr("src","blank");
        $("#menu_image1").hide();  
        $('#menu_images1').wrap('<form>').closest('form').get(0).reset();
        $('#menu_images1').unwrap();         
        return false;
    }   
    if(this.files[0].type !== 'image/png'){
        document.getElementById('e1').style.display = "block";
        if(document.getElementById("error1").innerText == 'Only png format allowed.'){
              document.getElementById("error1").innerHTML = '';
            }
            else{
            document.getElementById("error1").innerHTML = 'Only png format allowed.' ;
            }
        
        $("#menu_image1").attr("src","blank");
        $("#menu_image1").hide();  
        $('#menu_images1').wrap('<form>').closest('form').get(0).reset();
        $('#menu_images1').unwrap();         
        return false;
    }   
    console.log('reached required')
    reader.onload = function (e) {
      console.log(e.target.result)
        // get loaded data and render thumbnail.
        document.getElementById("menu_image1").src = e.target.result;
        $("#menu_image1").show(); 
    };

      reader.readAsDataURL(this.files[0]);

};

document.getElementById("menu_images2").onchange = function () {
    var reader = new FileReader();
    console.log('inside onchange handler')


      console.log('inside next handler')
        document.getElementById('e2').style.display = "none";
        var val = $(this).val().toLowerCase(),
            regex = new RegExp("(.*?)\.(ai|psd|cdr)$");

        if (!(regex.test(val))) {
            $(this).val('');
            document.getElementById('e2').style.display = "block";
            if(document.getElementById("error2").innerText == 'Please select only AI, PSD, CDR format file'){
              document.getElementById("error2").innerHTML = '';
            }
            else{
            document.getElementById("error2").innerHTML = "Please select only AI, PSD, CDR format file" ;
            }

            return false
        }


   reader.readAsDataURL(this.files[0]);
  
};

</script>


{% endblock step_three %}