Ercess/urls.py
from django.contrib import admin
from django.conf.urls import  url
from Ercesscorp import  views
from django.urls import  path ,re_path ,include
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Ercesscorp.apiviews import *

# app_name = 'Ercess'


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home , name='home'),

    url(r'^accounts/login/$',views.loginview ,name='login'),

    url(r'^live/dashboard/', include('dashboard.urls')),
   # url(r'^live/dashboard/organizer_dashboard',views.manageevents),
    

    url(r'^home/$', views.home, name='home'),
    url(r'^live/$',views.home , name='home'),
    url(r'^live/verify_email/(?P<slug>[\w-]+)/$', views.verify_mail),
#    url(r'^live/verify_email/$', views.verify_mail, name='verify-email'),
    url(r'^live/forgot_password/$', views.forgotPassword, name='forgot-password'),
    url(r'^live/reset_password/(?P<slug>[\w-]+)/$', views.resetPassword),
    url(r'^live/set_new_password/$', views.setNewPassword),
#    url(r'^live/reset_password/$', views.resetPassword,name='reset-password'),
    url(r'^live/login/$', views.loginview, name='login'),
    url(r'^live/logout/$', views.logoutview, name='logout'),
    url(r'^live/signup/$', views.registration,name='signup'),
    url(r'^live/multichannel/$',views.multichannelpromotion,name='multichannel-promotion'),
    url(r'^live/sell_event_stalls/$',views.sellstallspaces, name='sell-event-stalls'),
    url(r'^live/paid_advertisement/$', views.advertisement,name='advertisement'),
    url(r'^live/how_it_works/$',views.howitworks, name='how-it-works'),
    url(r'^live/about/$',views.aboutus,name='about-us'),
    url(r'^live/contact/$',views.contactus,name='contact-us'),
    url(r'^live/blogs/$', views.blog, name='blog'),
    url(r'^live/blog-post/(?P<pk>[0-9]+)$', views.blogpost,name='blog-post'),
    url(r'^live/careers/$', views.career, name='careers'),
    url(r'^live/pricing/$', views.pricing, name='pricing'),
    url(r'^live/partners/$', views.partners, name='partners'),
    url(r'^live/privacy_policy/$', views.privacypolicy , name='privacy-policy'),
    url(r'^live/api/blogs/$' , BlogDetails.as_view(),name='blog-details'),
    url(r'^live/api/blogs/(?P<pk>[0-9]+)$', BlogSpecific.as_view(),name='blogspecific'),
    url(r'^live/api/users/$', Reg.as_view(),name='reg'),
    url(r'^live/api/login/$', LoginView.as_view(),'loginview'),
]



if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)







dashboard/urls.py
from django.urls import path, include
from django.conf.urls import  url
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import TemplateView

from Ercesscorp.third_party_security import smartlogin
from Ercesscorp import views
from Ercesscorp.views import edit_event,step_three,step_three_action,edit_action_one,edit_event_two,edit_event_four,edit_action_four,edit_action_four
from dashboard.views import  getHow, change_password #, third_step#,photo_list ,fourth_step
from .api.views import ( ArticlesCreateAPIView, CategoryCreateAPIView, 
                        TopicsListAPIView, DescriptionCreateAPIView,
                        ThirdStepTemp, QuestionCreateAPIView,
                        CreateTicketsView, BankDetailsView)

from .views import  EditDetailView


app_name = 'dashboard'

urlpatterns = [
    url(r'^$', getHow, name='how'),
    path('add-event', ArticlesCreateAPIView.as_view(), name="step_one"),
    path('add-event-types/<str:md5>/<int:event_id>', CategoryCreateAPIView.as_view(), name="step_two"),
    path('add-event-images/<str:md5>/<int:event_id>', views.step_three, name="step_three"),
    path('add-event-images-action/<str:md5>/<int:event_id>', views.step_three_action, name="step_three_action"),
    path('ajax/topics', TopicsListAPIView.as_view()),
    path('add-event-description/<str:md5>/<int:event_id>', DescriptionCreateAPIView.as_view(), name="step_four"),
    path('add-event-tickets/<str:md5>/<int:event_id>', CreateTicketsView.as_view(), name="step_five"),
    path('add-event-question/<str:md5>/<int:event_id>', QuestionCreateAPIView.as_view(), name="step_six"),
    path('event_added', TemplateView.as_view(template_name='dashboard/event_success.html'), name='event_added'),
    path('RSVP',views.RSVP,name='leads'),
    path('rsvp/<int:event_id>',views.rsvp_event,name='rsvp-event'),
    path('organizer_dashboard',views.manageevents, name='organizer-dashboard'),
    path('event-details/<int:event_id>',views.event_details, name='event-details'),
    path('sales', views.getSales, name='sales'),
    path('sales_details/<int:event_id>/',views.getSalesDetails, name ='sale_details'),
    path('inquiries', views.getInquiries, name='inquiries'),
    path('help',views.getHelp,name='help'),
    path('profile',views.profile,name='profile'),
    path('settings', change_password,name='settings'),
    path('legal',views.legal,name='legal'),
    path('bank-details',BankDetailsView.as_view(), name="bank_details"),
    path('create-stalls',views.create_stall, name="create_stall"),
    path('edit-event/<int:event_id>', EditDetailView.as_view(), name="detail"),
    path('edit-event/basic/<int:event_id>',views.edit_event, name='edit-event'),
    path('edit-event-two/<int:event_id>',views.edit_event_two, name='edit-event-two'),
    path('edit-event-four/<int:event_id>',views.edit_event_four, name='edit-event-four'),
    path('edit_action_one/<event_id>',views.edit_action_one, name='edit-action-one'),
    path('edit_action_two/<event_id>',views.edit_action_two, name='edit-action-two'),
    path('edit_action_four/<event_id>',views.edit_action_four, name='edit-action-four'),
    #path('legal',views.legal,name='legal'),
    #url(r'create-event/step-three/(?P<eventid>[0-9]+)$',login_required(third_step),name='third-step'),
    #url(r'test$',photo_list),
    #url(r'create-event/step-four/$',login_required(fourth_step),name='fourth-step')
    # url(r'^home',home,name='home'),

    # url(r'^live/dashboard/organizer_dashboard',views.manageevents),
    # url(r'^live/dashboard/sales',views.salesreport),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from Ercesscorp.porter import HOW__CHOICES
from PIL import Image
from django import forms
from django.core.files import File
from .models import Articles2#,Photo



class HowForm(forms.Form):

    choices =  forms.ChoiceField(choices=HOW__CHOICES)
    other =  forms.CharField(widget=forms.Textarea(
        attrs={
            # 'class': 'form-control',
            'placeholder': 'if Others fill this *'
        }
    ))


class Articles2Form(forms.ModelForm):
    description = forms.CharField(widget=CKEditorWidget())
    class Meta:
        model = Articles2
        fields = ('description',)


class ChangePasswordForm(forms.Form):
	oldpassword = forms.CharField(
			widget=forms.PasswordInput(

				attrs={
					'class': 'form-control',
					'placeholder': 'Your old Password *'

				}
			)
		)
	newpassword1 = forms.CharField(
        widget=forms.PasswordInput(

            attrs={
                'class': 'form-control',
                'placeholder': 'New Password *'

            }
        )
    )
	newpassword2 = forms.CharField(
        widget=forms.PasswordInput(

            attrs={
                'class': 'form-control',
                'placeholder': 'Confirm New Password *'

            }
        )
    )
	def clean(self): 
            if len(self.cleaned_data['newpassword1'])<8:
                raise forms.ValidationError("New password is less than 8 characters")
            if self.cleaned_data['newpassword1'] != self.cleaned_data['newpassword2']:
                raise forms.ValidationError("The two password fields did not match.")
            return self.cleaned_data

'''
class PForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Articles2
        fields = ('company_logo','event_banner','editable_image','x', 'y', 'width', 'height', )

    def save(self):
        photo = super(PForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.company_logo)

        print('photo.file in form' +str(photo.company_logo))
        cropped_image = image.crop((x, y, w+x, h+y))
        print('cropped image in form' + str(cropped_image))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        print('resize image in form' + str(resized_image))
        resized_image.save(photo.company_logo.path)
        print(photo.company_logo.path)
        # print(photo)
        return photo




class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Photo
        fields = ('file','x', 'y', 'width', 'height', )

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        print(image)
        print('photo.file in form' +str(photo.file))
        cropped_image = image.crop((x, y, w+x, h+y))
        print('cropped image in form' + str(cropped_image))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        print('resize image in form' + str(resized_image))
        resized_image.save(photo.file.path)
        print(photo.file.path)
        return photo


'''


templates/dashboard/create_event.html
  {% load static %}

  <!DOCTYPE html>
  <html>
     <head>

         <meta charset="UTF-8">

         <title>{% block title %} {% endblock title %}</title>
  {#<!--#}
  {#<link rel="stylesheet" href="{% static 'assets/vendor_components/font-awesome/css/font-awesome.css' %}" type="text/css">#}
  {#	<link rel="stylesheet" href="{% static 'assets/vendor_components/font-awesome/css/font-awesome-animation.css' %}" type="text/css">#}
  {#        <link rel="stylesheet" href="{% static 'assets/vendor_components/Ionicons/css/ionicons.css' %}" type="text/css">#}
  {#        <link rel="stylesheet" href="{% static 'assets/vendor_components/themify-icons/themify-icons.css' %}" type="text/css">#}
  {#        <link rel="stylesheet" href="{% static 'assets/vendor_components/linea-icons/linea.css' %}" type="text/css">#}
  {#        <link rel="stylesheet" href="{% static 'assets/vendor_components/glyphicons/glyphicon.css' %}" type="text/css">#}
  {#        <link rel="stylesheet" href="{% static 'assets/vendor_components/flag-icon/css/flag-icon.css' %}" type="text/css">#}
  {#        <link rel="stylesheet" href="{% static 'assets/vendor_components/animate/animate.css' %}" type="text/css">#}
  {#        <link rel="stylesheet" href="{% static 'assets/vendor_components/simple-line-icons-master/css/simple-line-icons.css' %}" type="text/css">#}
  {#        <link rel="stylesheet" href="{% static 'assets/vendor_components/material-design-iconic-font/css/materialdesignicons.css' %}" type="text/css">#}
  {#-->#}


          <link rel="shortcut icon" href="/static/images/fav.ico">
         <link rel="stylesheet" href="{% static 'dashboard/main.css' %}" type="text/css">
         <!--  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>-->
  		<script src="{% static 'assets/vendor_components/jquery-3.3.1/jquery-3.3.1.js' %}"></script> 
           <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>  
          <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.0/dist/jquery.validate.js"></script>
  	<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.0/dist/additional-methods.js"></script>

  	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.0.1/jquery-migrate.min.js"></script>
        <!--  <script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.7/jquery.validate.min.js"></script>
  	<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/additional-methods.js"></script> -->
  	      <script src="{% static 'dashboard/main.js' %}"></script>
  	<link rel="stylesheet" href="https://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" type="text/css">


  {#    for replacing name at field of uploads   #}

  {#  bootstrap cdns      #}

       <meta name="viewport" content="width=device-width, initial-scale=1">
      <!--link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script-->
      <!--script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script-->

  	<!-- DateTime Picker -->
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.19.3/moment-with-locales.min.js"></script>
  	<script src="{% static 'assets/vendor_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  	<script type="text/javascript" src="https://code.jquery.com/ui/1.10.0/jquery-ui.js"></script>
  	<link rel="stylesheet" href="{% static 'dashboard/modified-datetime.css' %}" type="text/css">
  	<script src="{% static 'dashboard/modified-datetime.js' %}"></script>
  	<link rel="stylesheet" href="{% static 'assets/vendor_components/bootstrap/dist/css/bootstrap.min.css' %}" type="text/css">



  	<!-- Date Picker -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>



  	
  {#  google fonts    #}
         <link href="https://fonts.googleapis.com/css?family=Overpass" rel="stylesheet">

        <!-- Bootstrap extend-->
        <link rel="stylesheet" href="{% static 'css/bootstrap-extend.css' %}" type="text/css">	

        
        <!-- Theme style -->
        <link rel="stylesheet" href="{% static 'css/master_style.css' %}" type="text/css">
        <link rel="stylesheet" href="{% static 'css/skins/_all-skins.css' %}" type="text/css">	
        <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script> -->



  {#   for cropping#}
     <link href="{% static 'img_cpr/css/cropper.min.css' %}" rel="stylesheet">
     <script src="{% static 'img_cpr/js/cropper.min.js' %}"></script>


     {% block RSVP_head %}
     {% endblock RSVP_head %}
     {% block og_head %}
     {% endblock og_head %}
  {% block javascript%}

  {% endblock javascript %}
  	
   </head>
   <body class="hold-transition skin-purple-light sidebar-mini bg-black">
  <div class='wrapper'>
       <header class="main-header">
  		   <!-- Logo -->
              <a href="{% url 'dashboard:how' %}" class="logo">
                  <span class="logo-lg">
                      <img src="{% static 'images/logo.png' %}" alt="logo" class="light-logo">
                  </span>
              </a>
  		    <nav class="navbar navbar-static-top">
  			<!-- Sidebar toggle button-->
        <a href="#"  data-toggle="push-menu" role="button" class="d-block d-sm-none">
          <i style="color: white;" class="glyphicon glyphicon-resize-horizontal"></i>
          <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
        </a>
  		  <div></div>
  	<div class="navbar-custom-menu">
          	<ul class="nav navbar-nav">
  		  	
            		<li class="dropdown user user-menu">
              		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
                		<img src="{% static 'images/user-avatar.jpg' %}" class="user-image rounded-circle b-2">
  				          <span class="font-size-14">{{ request.session.firstname }} {{ request.session.lastname }}<i class="mdi mdi-chevron-down"></i></span>
              		</a>
              		<ul class="dropdown-menu scale-up">
                		<!-- Menu Body -->
                		<li class="user-body bt-0">
                  	<div class="row no-gutters">
                    		<!-- <div class="col-12 text-left">
                      		  <a href="{% url 'dashboard:profile' %}"><i class="glyphicon glyphicon-user"></i> My Profile</a>
                    		</div> -->
                    		
                    		<div class="col-12 text-left">
                      		  <a href="{% url 'dashboard:settings' %}"><i class="glyphicon glyphicon-cog"></i> Settings</a>
                    		</div>
  				
  				  <div role="separator" class="divider col-12"></div>
  				    <div class="col-12 text-left">
                     			 <a href="{% url 'logout' %}"><i class="fa fa-power-off"></i> Logout</a>
                    		    </div>				
                  		 </div>
                  		<!-- /.row -->
                		</li>
             	 </ul>
            	</li>
             </ul>
  	      </div>
  	</nav>
       </header>
  <!-- Left side column. contains the logo and sidebar -->
    <aside class="main-sidebar">
      <!-- sidebar-->
      <section class="sidebar">
        
        <!-- sidebar menu-->
        <ul class="sidebar-menu pt-20" data-widget="tree">
            <li >
              <a href="{% url 'dashboard:how' %}">
                <i class="glyphicon glyphicon-home"></i> <span>Home</span>
              </a>
  	        </li>
            <li >
             <a href="{% url 'dashboard:organizer-dashboard' %}">
              <i class="glyphicon glyphicon-wrench"></i> <span>Manage events</span>
            </a>
          </li>
            <li >
             <a href="{% url 'dashboard:step_one' %}">
              <i class="glyphicon glyphicon-plus"></i> <span>Create events</span>
            </a>
          </li>
          <li >
            <a href="{% url 'dashboard:create_stall' %}">
             <i class="glyphicon glyphicon-plus"></i> <span>Create stalls</span>
           </a>
         </li>
            <li >
             <a href="{% url 'dashboard:sales' %}">
              <i class="glyphicon glyphicon-signal"></i> <span>Sales report</span>
            </a>
          </li>
            <li >
             <a href="{% url 'dashboard:leads' %}">
              <i class="glyphicon glyphicon-tags"></i> <span>RSVP</span>
            </a>
          </li>
            <!-- <li >
             <a href="{% url 'dashboard:inquiries' %}">
              <i class="glyphicon glyphicon-earphone"></i> <span>Customer inquiries</span>
            </a>
          </li> -->
            <li >
             <a href="{% url 'dashboard:legal' %}">
              <i class="glyphicon glyphicon-tags"></i> <span>Legal</span>
            </a>
          </li>
            <li >
             <a href="{% url 'dashboard:bank_details' %}">
              <i class="glyphicon glyphicon-usd"></i> <span>Bank details</span>
            </a>
          </li>
            <li >
             <a href="{% url 'dashboard:help' %}">
              <i class="glyphicon glyphicon-book"></i> <span>Help Center</span>
            </a>
          </li>

        </ul>
      </section>
    </aside>
    <div class="content-wrapper" >
  		{% block step_one %}
  		{% endblock step_one %}
                  {% block step_two %}
  		{% endblock step_two %}
                  {% block step_three %}
  		{% endblock step_three %}
                  {% block step_four %}
  		{% endblock step_four %}
                  {% block step_six %}
  		{% endblock step_six %}
                  {% block step_success %}
                  {% endblock step_success %}  
  		{% block RSVP %}
  		{% endblock RSVP %}
  		{% block og %}
  		{% endblock og %}
    </div>    


          {% include "dashboard/footer.html" %}
    
    <div class="control-sidebar-bg"></div>
  </div>

      <!-- jQuery 3 
  	<script src="{% static 'assets/vendor_components/jquery-3.3.1/jquery-3.3.1.js' %}"></script> -->
  	<script src="{% static 'assets/vendor_components/screenfull/screenfull.js' %}"></script>
  	<script src="{% static 'assets/vendor_components/popper/dist/popper.min.js' %}"></script>
  	
  	<!-- Bootstrap 4.1
  	<script src="{% static 'assets/vendor_components/bootstrap/dist/js/bootstrap.min.js' %}"></script>-->
  	<script src="{% static 'assets/vendor_components/jquery-slimscroll/jquery.slimscroll.min.js' %}"></script>
  	<script src="{% static 'assets/vendor_components/fastclick/lib/fastclick.js' %}"></script>
  	<script src="{% static 'js/template.js' %}"></script>
    </body>
</html>

templates/dashboard/inquiries.html
{% extends 'dashboard/create_event.html' %}

{% block title %} Customer inquiries - Ercess Live {% endblock title %}
{% block og %}







{% endblock og %}

templates/dashboard/photo_list.html
{% extends 'base.html' %}

{% block javascript %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
          var reader = new FileReader();
          reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
          }
          reader.readAsDataURL(this.files[0]);
        }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
      var canvasData;
      $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
          viewMode: 1,
          aspectRatio: 1/1,
          minCropBoxWidth: 200,
          minCropBoxHeight: 200,
          ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
          }
        });
      }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
      });

      $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
      });

      $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
      });

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>
{% endblock %}

{% block content %}
  <h1 class="page-header">Album</h1>

  <!-- FORM TO UPLOAD THE IMAGES -->
  <form method="post" enctype="multipart/form-data" id="formUpload">
    {% csrf_token %}
    {{ form }}
  </form>

  <!-- MODAL TO CROP THE IMAGE -->
  <div class="modal fade" id="modalCrop">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4 class="modal-title">Crop the photo</h4>
        </div>
        <div class="modal-body">
          <img src="" id="image" style="max-width: 100%;">
        </div>
        <div class="modal-footer">
          <div class="btn-group pull-left" role="group">
            <button type="button" class="btn btn-default js-zoom-in">
              <span class="glyphicon glyphicon-zoom-in"></span>
            </button>
            <button type="button" class="btn btn-default js-zoom-out">
              <span class="glyphicon glyphicon-zoom-out"></span>
            </button>
          </div>
          <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
          <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
        </div>
      </div>
    </div>
  </div>

  <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
  <div class="row" style="margin-top: 20px">
    {% for photo in photos %}
      <div class="col-sm-4 col-md-3">
        <img src="{{ photo.file.url }}" class="thumbnail">
      </div>
    {% endfor %}
  </div>

{% endblock %}

templates/dashboard/sale_details.html
{% extends 'dashboard/create_event.html' %}

{% block title %} Sale details - Ercess Live {% endblock title %}
{% block og %}
<section class="content">
  <div class="container arrow-steps clearfix">
    <div class="row">
      <div class="col-md-12">
          <h1 class="text-dark mb-30">Sales Details</h1>
          <h2 class="text-dark mb-30" align='center'>{{eve_name}}</h2>
          {% if count == 0 %}
          <div class="alert alert-info text-center mb-80">
              <h4> NO DETAILS OF THE SALE </h4>
          </div>
          {% else %}
          <div class="table-responsive">
            <table class="table table-hover table-event-list">
              <thead>
                <th>Ticket Type</th>
                <th>Booking Id</th>
                <th>Amount</th>
                <th>Quantity</th>
                <th>Purchase Date</th>
                <th>Seller Site</th>
                <th>Attendee</th>
              </thead>
              {% for type,id,amt,qty,p_date,site,atten in details %}
              <tr>
                <td>{{type}}</td>
                <td>{{id}}</td>
                <td>{{amt}}</td>
                <td>{{qty}}</td>
                <td>{{p_date.date}}</td>
                <td>{{site}}</td>
                <td>{{atten}}</td>
              </tr>
              {% endfor %}
            </table>
          </div>
          {% endif %}
      </div>
    </div>
  </div>
</section>

{% endblock og %}